# Generated by Django 5.2 on 2025-04-13 15:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0002_remove_expenses_id_expenses_expense_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="expenses",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
